<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<title>Lab 1</title>
	<style>
		span {
			display: inline-block;
			font-weight: bold;
			margin-bottom: 5px;
		}
		form {
			margin-bottom: 20px;
		}
	</style>
</head>

<body>
	<?php
		isConnectionSet($dbh);
	?>

	<span>Вывести список компьютеров с центральным процессором</span>
	<form action="/handler/cpu" method="get">
		<select name="cpuList">
			<?php
				include_once "lists/cpu.php";
			?>
		</select>
		<input type="submit" name="getBtn" value="Ok">
	</form>

	<span>Вывести список компьютеров с установленным ПО</span>
	<form action="/handler/software" method="get">
		<select name="softwareList">
			<?php
				include_once "lists/software.php";
			?>
		</select>
		<input type="submit" name="getBtn" value="Ok">
	</form>

	<span>Вывести список компьютеров с истёкшим гарантийным сроком</span>
	<form action="/handler/guarantee" method="get">
		<label>Выберите дату: <input type="date" name="guaranteeDate" min="2015-01-01" max="2025-12-31" value="2022-05-16"></label>
		<input type="submit" name="getBtn" value="Ok">
	</form>
</body>
</html>